In [3]:
%pylab inline
import pandas as pd
import seaborn as sns
import numpy as np
import scipy 
import matplotlib.pyplot as plt
import matplotlib.style as style
from sklearn.ensemble import RandomForestRegressor
import sys
from sklearn.model_selection import train_test_split
import pydot
#imports the own created package

from sklearn.tree import export_graphviz

import warnings
warnings.filterwarnings('ignore')

Populating the interactive namespace from numpy and matplotlib

In [42]:
#imports pickle file created and saved in 'load_and_clean.ipynb'
df_both_seasons_home = pd.read_pickle('df_both_seasons_essentials')
df_both_seasons_home.head()

,Day,Month,Year,HomeTeam,AwayTeam,FTHG,FTAG,HST,AST,HTR,HTGDIFF,ATGDIFF
0,9,12,2020,Fulham,Arsenal,0,3,2,6,0,-3,3
1,9,12,2020,Crystal Palace,Southampton,1,0,3,5,2,1,-1
2,9,12,2020,Liverpool,Leeds,4,3,6,3,2,1,-1
3,9,12,2020,West Ham,Newcastle,0,2,3,2,1,-2,2
4,13,9,2020,West Brom,Leicester,0,3,1,7,1,-3,3

In [43]:
def avg_goal_diff(df, column_name, a_h_team, a_h_goal_letter):
    """
    input: 
        df = dataframe with all results
       column_name = name of the new column
        a_h_team = HomeTeam or AwayTeam
        a_h_goal_letter = 'H' for home or 'A' for away
    output: 
        df: dataframe with a new column (H/A)TGDIFF
       
    """
    df[column_name] = 0
    avg_per_team = {}
    all_teams = df[a_h_team].unique()
    for t in all_teams:
        df_team = df[df[a_h_team]==t].fillna(0) ##we fill rows that have no values with 0
        result = df_team['{}TGDIFF'.format(a_h_goal_letter)].rolling(10).mean()
        df_team[column_name] = result.shift(-9)
        avg_per_team[t] = df_team
        
    df2 = pd.DataFrame()
    for v in avg_per_team.values():
        df2 = df2.append(v)
    return df2
    
    
def avg_points(df,column_name, h_or_a_team, h_or_a_letter):
    """
    input: 
        df = dataframe with all results
        column_name = name of the new column
        a_h_team = HomeTeam or AwayTeam
        a_h_goal_letter = 'H' for home or 'A' for away
    """
    df[column_name] = 0
    avg_points_team = {}
    all_teams = df[h_or_a_team].unique()
    for t in all_teams:
        df_team = df[df[h_or_a_team]==t].fillna(0)
        result = df_team['HTR'].rolling(10).mean()
        df_team[column_name] = result.shift(-9)
        avg_points_team[t] = df_team
    df2 = pd.DataFrame()
    for v in avg_points_team.values():
        df2 = df2.append(v)
    return df2

In [54]:
df_both_seasons=avg_goal_diff(df_both_seasons_home, 'AVGHTGDIFF', 'HomeTeam', 'H')
df_both_seasons.head()

,Day,Month,Year,HomeTeam,AwayTeam,FTHG,FTAG,HST,AST,HTR,HTGDIFF,ATGDIFF,AVGHTGDIFF,AVGP
0,9,12,2020,Fulham,Arsenal,0,3,2,6,0,-3,3,0.1,0
26,28,9,2020,Fulham,Aston Villa,0,3,3,5,0,-3,3,0.4,0
50,24,10,2020,Fulham,Crystal Palace,1,2,3,10,0,-1,1,0.8,0
66,11,2,2020,Fulham,West Brom,2,0,6,1,2,2,-2,0.6,0
82,22,11,2020,Fulham,Everton,2,3,6,7,0,-1,1,0.5,0

In [29]:
df_both_seasons=df_both_seasons.sort_values(['Year', 'Month','Day'], ascending=False)

In [55]:
df_both_seasons=avg_points(df_both_seasons_home, 'AVGP', 'HomeTeam', 'H')

In [46]:
df_both_seasons.head()

,Day,Month,Year,HomeTeam,AwayTeam,FTHG,FTAG,HST,AST,HTR,HTGDIFF,ATGDIFF,AVGHTGDIFF,AVGP
0,9,12,2020,Fulham,Arsenal,0,3,2,6,0,-3,3,0,0.8
26,28,9,2020,Fulham,Aston Villa,0,3,3,5,0,-3,3,0,0.8
50,24,10,2020,Fulham,Crystal Palace,1,2,3,10,0,-1,1,0,1.0
66,11,2,2020,Fulham,West Brom,2,0,6,1,2,2,-2,0,1.0
82,22,11,2020,Fulham,Everton,2,3,6,7,0,-1,1,0,0.9

In [47]:
df_both_seasons=df_both_seasons.sort_values(['Year', 'Month','Day'], ascending=False)

In [36]:
df_both_seasons.columns

Index(['Day', 'Month', 'Year', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'HST',
       'AST', 'HTR', 'HTGDIFF', 'ATGDIFF', 'AVGHTGDIFF', 'AVGP'],
      dtype='object')

In [48]:
df_both_seasons.head()

,Day,Month,Year,HomeTeam,AwayTeam,FTHG,FTAG,HST,AST,HTR,HTGDIFF,ATGDIFF,AVGHTGDIFF,AVGP
0,9,12,2020,Fulham,Arsenal,0,3,2,6,0,-3,3,0,0.8
1,9,12,2020,Crystal Palace,Southampton,1,0,3,5,2,1,-1,0,1.2
2,9,12,2020,Liverpool,Leeds,4,3,6,3,2,1,-1,0,1.8
3,9,12,2020,West Ham,Newcastle,0,2,3,2,1,-2,2,0,1.4
347,7,12,2020,Tottenham,Arsenal,2,1,9,4,1,1,-1,0,NaN

In [51]:
df_both_seasons["AVGP"].fillna(value=df_both_seasons["AVGP"].mean(),inplace=True)

In [53]:
df_both_seasons.head(20)

,Day,Month,Year,HomeTeam,AwayTeam,FTHG,FTAG,HST,AST,HTR,HTGDIFF,ATGDIFF,AVGHTGDIFF,AVGP
0,9,12,2020,Fulham,Arsenal,0,3,2,6,0,-3,3,0,0.800000
1,9,12,2020,Crystal Palace,Southampton,1,0,3,5,2,1,-1,0,1.200000
2,9,12,2020,Liverpool,Leeds,4,3,6,3,2,1,-1,0,1.800000
3,9,12,2020,West Ham,Newcastle,0,2,3,2,1,-2,2,0,1.400000
347,7,12,2020,Tottenham,Arsenal,2,1,9,4,1,1,-1,0,1.113855
346,7,12,2020,Aston Villa,Crystal Palace,2,0,9,5,2,2,-2,0,1.113855
345,7,12,2020,Wolves,Everton,3,0,7,2,2,3,-3,0,1.113855
348,7,12,2020,Bournemouth,Leicester,4,1,4,5,0,3,-3,0,1.113855
382,2,12,2020,Reading,West Brom,1,2,1,7,1,-1,1,0,1.113855
381,2,12,2020,Millwall,Fulham,1,1,2,2,1,0,0,0,1.113855
218,1,12,2020,Aston Villa,Man City,1,6,1,12,0,-5,5,0,1.113855
217,1,12,2020,Bournemouth,Watford,0,3,1,6,0,-3,3,0,1.113855
97,30,11,2020,West Ham,Aston Villa,2,1,2,6,1,1,-1,0,1.200000
96,30,11,2020,Leicester,Fulham,1,2,3,5,0,-1,1,0,0.900000
95,29,11,2020,Arsenal,Wolves,1,2,2,5,0,-1,1,0,0.800000
93,29,11,2020,Southampton,Man United,2,3,5,6,2,-1,1,0,0.400000
94,29,11,2020,Chelsea,Tottenham,0,0,3,1,1,0,0,0,1.100000
92,28,11,2020,West Brom,Sheffield United,1,0,6,5,2,1,-1,0,1.200000
89,28,11,2020,Brighton,Liverpool,1,1,3,2,1,0,0,0,1.100000
91,28,11,2020,Everton,Leeds,0,1,8,7,1,-1,1,0,1.300000